kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    type: my_jenkin_pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0a8c38e313bec107b
    fsType: ext4
