apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-root-volume
  namespace: jenkins                    # make sure you have namespace jenkins created if not remove this line  
  labels:
    type: aws-ebs-volume
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-0a8c38e313bec107b      # your volume id you will get this form aws 
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
  namespace: jenkins
  labels:
    type: aws-ebs-volume
spec:
  storageClassName: ""      
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: my-root-volume
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  serviceName: "jenkins"
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins-master
          image: jenkins/jenkins:lts
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
          volumeMounts:
          - mountPath: "/var/jenkins_home"
            name: contaner-volume
          securityContext:
            runAsUser: 0
      volumes:
        - name:  contaner-volume
          persistentVolumeClaim:
            claimName: my-volume-claim
